<?php 
/**
 * @Title: Config
 * @Package package_name
 * @Description: todo(动态表单_配置文件-list.inc 配置文件)
 * @author 管理员
 * @company 重庆特米洛科技有限公司
 * @copyright 本文件归属于重庆特米洛科技有限公司
 * @date 2018-09-18 09:20:36
 * @version V1.0
*/
$original = array(
	'id' => array(
		'name' => 'id',
		'showname' => 'ID',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'status' => '1',
		'sortname' => 'id',
		'sortnum' => '0',
		'searchField' => 'mis_auto_cdzws.id',
		'conditions' => '',
		'type' => 'text',
		'issearch' => '1',
		'message' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'updateid' => array(
		'name' => 'updateid',
		'showname' => '修改人',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'updateid',
		'sortnum' => '0',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_cdzws.updateid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '0',
	),
	'companyid' => array(
		'name' => 'companyid',
		'showname' => '公司',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'MisSystemCompany',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
		'sortname' => 'companyid',
		'sortnum' => '22',
		'issearch' => '1',
		'table' => 'mis_system_company',
		'searchField' => 'mis_auto_cdzws.companyid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'MisSystemCompany',
				),
			),
		),
	),
	'departmentid' => array(
		'name' => 'departmentid',
		'showname' => '部门',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'departmentid',
		'sortnum' => '2',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_cdzws.departmentid',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '2',
	),
	'orderno' => array(
		'name' => 'orderno',
		'showname' => '编号',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'orderno',
		'sortnum' => '3',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => '',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_cdzws.orderno',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '1',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '3',
	),
	'text7' => array(
		'name' => 'text7',
		'showname' => '短文本框_7',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'text7',
		'sortnum' => '4',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_cdzws.text7',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '4',
	),
	'ly' => array(
		'name' => 'ly',
		'showname' => '判断',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'ly',
		'sortnum' => '5',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => '',
		'relation' => '',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'text',
		'searchField' => 'mis_auto_cdzws.ly',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '5',
	),
	'lookup5' => array(
		'name' => 'lookup5',
		'showname' => 'lookup组件 _5',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'lookup5',
		'sortnum' => '6',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'lookup',
		'searchField' => 'mis_auto_cdzws.lookup5',
		'conditions' => '',
		'type' => 'db|',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => '',
				),
			),
		),
		'table' => '',
		'field' => 'id',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '6',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => '',
				),
			),
		),
	),
	'select11' => array(
		'name' => 'select11',
		'showname' => '下拉框_11',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'select11',
		'sortnum' => '7',
		'shows' => '1',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_cdzws.select11',
		'conditions' => '',
		'type' => 'select',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '7',
	),
	'date7' => array(
		'name' => 'date7',
		'showname' => '日期组件_7',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'date7',
		'sortnum' => '8',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_cdzws.date7',
		'conditions' => '',
		'type' => 'time',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transTime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '8',
		'unfunc' => array(
			'0' => array(
				'0' => 'untransTime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'Y-m-d',
				),
			),
		),
	),
	'password8' => array(
		'name' => 'password8',
		'showname' => '密码框_8',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'password8',
		'sortnum' => '9',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'password',
		'searchField' => 'mis_auto_cdzws.password8',
		'conditions' => '',
		'type' => 'text',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'func' => array(
			'0' => array(
				'0' => 'passwordChange',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '9',
	),
	'hiddens10' => array(
		'name' => 'hiddens10',
		'showname' => '隐藏域组件_10',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'hiddens10',
		'sortnum' => '10',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'hiddens',
		'searchField' => 'mis_auto_cdzws.hiddens10',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'ischosice' => '1',
	),
	'textarea16' => array(
		'name' => 'textarea16',
		'showname' => '文本域_16',
		'widths' => '350',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'textarea16',
		'sortnum' => '11',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'textarea',
		'searchField' => 'mis_auto_cdzws.textarea16',
		'conditions' => '',
		'type' => 'textarea',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '11',
	),
	'select26' => array(
		'name' => 'select26',
		'showname' => '下拉框_26',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'select26',
		'sortnum' => '12',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'select',
		'searchField' => 'mis_auto_cdzws.select26',
		'conditions' => '',
		'type' => 'select',
		'validate' => NULL,
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '12',
	),
	'checkbox28' => array(
		'name' => 'checkbox28',
		'showname' => '复选框_28',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'checkbox28',
		'sortnum' => '13',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'checkbox',
		'searchField' => 'mis_auto_cdzws.checkbox28',
		'conditions' => '',
		'type' => 'checkbox',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
					'2' => 'checkbox',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
					'2' => 'checkbox',
				),
			),
		),
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '13',
	),
	'upload30' => array(
		'name' => 'upload30',
		'showname' => '上传组件_30',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'upload30',
		'sortnum' => '14',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'upload',
		'searchField' => 'mis_auto_cdzws.upload30',
		'conditions' => '',
		'type' => 'upload',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
	),
	'radio29' => array(
		'name' => 'radio29',
		'showname' => '单选框_29',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'radio29',
		'sortnum' => '15',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'radio',
		'searchField' => 'mis_auto_cdzws.radio29',
		'conditions' => '',
		'type' => 'select',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '1',
		'func' => array(
			'0' => array(
				'0' => 'getSelectlistValue',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetSelectlistValue',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '',
				),
			),
		),
		'issearch' => '1',
		'isallsearch' => '0',
		'searchsortnum' => '15',
	),
	'areainfo31' => array(
		'name' => 'areainfo31',
		'showname' => '地址组件：_31',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areainfo31',
		'sortnum' => '16',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'areainfo',
		'searchField' => 'mis_auto_cdzws.areainfo31',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '16',
	),
	'areainfo33' => array(
		'name' => 'areainfo33',
		'showname' => '地址组件：_33',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'areainfo33',
		'sortnum' => '17',
		'shows' => '0',
		'status' => '1',
		'rules' => '1',
		'message' => '1',
		'isexport' => '1',
		'methods' => 'view',
		'relation' => 'orderno',
		'fieldtype' => 'varchar',
		'fieldcategory' => 'areainfo',
		'searchField' => 'mis_auto_cdzws.areainfo33',
		'conditions' => '',
		'type' => 'text',
		'validate' => '',
		'unique' => '0',
		'required' => '0',
		'transform' => '0',
		'issearch' => '1',
		'isallsearch' => '1',
		'searchsortnum' => '17',
	),
	'auditState' => array(
		'name' => 'auditState',
		'showname' => '审核状态',
		'shows' => '1',
		'rules' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'auditState',
		'func' => array(
			'0' => array(
				'0' => 'getAuditState',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => '#id#',
					'2' => '#ptmptid#',
				),
			),
		),
		'sortnum' => '20',
		'searchField' => 'mis_auto_cdzws.auditState',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'operateid' => array(
		'name' => 'operateid',
		'showname' => '是否确认',
		'rules' => '1',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'func' => array(
			'0' => array(
				'0' => 'getSelectByName',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => 'operateidVal',
					'1' => '###',
				),
			),
		),
		'sortname' => 'operateid',
		'sortnum' => '21',
		'searchField' => 'mis_auto_cdzws.operateid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'projectid' => array(
		'name' => 'projectid',
		'showname' => '项目ID',
		'rules' => '0',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'projectid',
		'sortnum' => '22',
		'searchField' => 'mis_auto_cdzws.projectid',
		'transform' => '0',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
	),
	'createid' => array(
		'name' => 'createid',
		'rules' => '1',
		'showname' => '创建人',
		'shows' => '0',
		'widths' => '',
		'sorts' => '0',
		'models' => 'User',
		'func' => array(
			'0' => array(
				'0' => 'getFieldBy',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
		'sortname' => 'createid',
		'issearch' => '1',
		'table' => 'user',
		'sortnum' => '23',
		'searchField' => 'mis_auto_cdzws.createid',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'ungetFieldBy',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
					'1' => 'id',
					'2' => 'name',
					'3' => 'User',
				),
			),
		),
	),
	'createtime' => array(
		'name' => 'createtime',
		'showname' => '创建时间',
		'shows' => '1',
		'widths' => '',
		'sorts' => '0',
		'models' => '',
		'sortname' => 'createtime',
		'sortnum' => '24',
		'fieldtype' => 'date',
		'fieldcategory' => 'date',
		'searchField' => 'mis_auto_cdzws.createtime',
		'conditions' => '',
		'type' => 'time',
		'issearch' => '0',
		'isallsearch' => '0',
		'searchsortnum' => '1',
		'func' => array(
			'0' => array(
				'0' => 'transtime',
			),
		),
		'funcdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
		'helpvalue' => '',
		'transform' => '1',
		'unique' => '0',
		'validate' => '0',
		'required' => '0',
		'unfunc' => array(
			'0' => array(
				'0' => 'untranstime',
			),
		),
		'unfuncdata' => array(
			'0' => array(
				'0' => array(
					'0' => '###',
				),
			),
		),
	),
);

$extedsList = require 'listExtend.inc.php';
return array_merge($original , $extedsList);
?>